### PR TITLE
Add Bartosz Jarzyna

### PR DESCRIPTION
**Pull request by bbrtj**

### CODE REVIEW

**Comment by jest** [comment]
Thanks for the update.

@brtastic I'm no longer programming in Perl, so maybe you are interested in taking the module and being a primary maintainer on PAUSE (https://www.cpan.org/modules/04pause.html)?

**Comment by bbrtj** [comment]
@jest Yes, I'll be happy to.

**Comment by bbrtj** [comment]
@jest you already know my PAUSE ID, so feel free to grant me the permissions on PAUSE. I guess I can then use my fork to release, so no github permissions are needed. I will just need to change the github repository in the metadata

**Comment by jest** [comment]
@bbrtj Done. Sorry to keep you so long; had to regain my long forgotten PAUSE credentials. :)

**Comment by bbrtj** [comment]
@jest thanks, released version 0.04 with github links pointing to my fork

**Pull request merged**
